name: Notify Slack

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      title:
        required: true
        type: string 
      message:
        required: true
        type: string
      color:
        required: false
        type: string
        default: good
        description: "Some options [good, danger, #808080]"
      icon:
        required: false
        type: string
        default: https://raw.githubusercontent.com/alice-biometrics/custom-emojis/master/images/alice_bot.png
      icon-emoji:
        required: false
        type: string
        default: "not_set"
      username:
        required: false
        type: string
        default: Alice Bot
    secrets:
      slack_token:
        required: true

env:
  SLACK_CHANNEL: ${{ inputs.channel }}  
  SLACK_TITLE: ${{ inputs.title }}  
  SLACK_MESSAGE: ${{ inputs.message }}  
  SLACK_USERNAME: ${{ inputs.username }}
  SLACK_FOOTER: 'Repository: ${{ github.repository }}'
  SLACK_COLOR: ${{ inputs.color }}  
  MSG_MINIMAL: actions url

jobs:
  notify-slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Set environment variables
      run: |
        if [[ ${{ inputs.icon-emoji }} == "not_set" ]]; then
          echo "SLACK_ICON=${{ inputs.icon }}" >> $GITHUB_ENV
        else
          echo "SLACK_ICON_EMOJI=${{ inputs.icon-emoji }}" >> $GITHUB_ENV
        fi
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL:  ${{ env.SLACK_CHANNEL }}
        SLACK_USERNAME: ${{ env.SLACK_USERNAME }}
        SLACK_TITLE: ${{ env.SLACK_TITLE }}
        SLACK_MESSAGE: ${{ env.SLACK_MESSAGE }}
        SLACK_COLOR: ${{ env.SLACK_COLOR }}
        SLACK_WEBHOOK: ${{ secrets.slack_token }}
        MSG_MINIMAL: ${{ env.MSG_MINIMAL }}
        SLACK_FOOTER: ${{ env.SLACK_FOOTER }}
