name: Release update

on:
  release:
    types: [published]

env:
  ALICE_GITHUB_ACCESS_TOKEN: ${{ secrets.PUBLIC_GITHUB_ACCESS_TOKEN }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  react-demo-release-update:
    name: React Demo release update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set RELEASE_VERSION
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
      - name: Install latest sdk version
        run: |
          yarn add aliceonboarding@${RELEASE_VERSION}
      - name: Build react demo
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn react-scripts build
      - name: Git - Update changes
        run: |
          git config --global user.email "dev@alicebiometrics.com"
          git config --global user.name "Alice Biometrics"
          yarn version --new-version ${RELEASE_VERSION} --no-git-tag-version
      - name: Git - Commit changes
        run: |
          git config --global user.email "dev@alicebiometrics.com"
          git config --global user.name "ALiCE Biometrics"
          git add -u
          git commit -m "feat: update version to ${RELEASE_VERSION}"
      - name: Push changes
        uses: alice-biometrics/github-push-action@master
        with:
          github_token: ${{ secrets.PUBLIC_GITHUB_ACCESS_TOKEN }}
          branch: master

  notify-success:
    needs: [react-demo-release-update]
    if: ${{ !contains(github.event.release.tag_name, 'rc') && success() }}
    uses: alice-biometrics/actions/.github/workflows/notify-slack.yml@v1.55
    with:
      channel: releases
      title: Success on Release Workflow
      message: "Onboarding web react demo successfully updated :rocket:"
      icon-emoji: ":react:"
      username: React demo
    secrets:
      slack_token: ${{ secrets.SLACK_WEBHOOK_PRODUCTION }}

  notify-failure:
    needs: [react-demo-release-update]
    if: ${{ !contains(github.event.release.tag_name, 'rc') && failure() }}
    uses: alice-biometrics/actions/.github/workflows/notify-slack.yml@v1.55
    with:
      channel: releases
      title: Failure on Release Workflow
      message: ${{ needs.build.outputs.failure_info }}
      icon-emoji: ":react:"
      username: React demo
      color: danger
    secrets:
      slack_token: ${{ secrets.SLACK_WEBHOOK_PRODUCTION }}
